name: Check code style
on: [push, pull_request]

jobs:
  php:
    name: PHP
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run PHP_CodeSniffer
        uses: ./.github/actions/phpcs-action
        with:
          args: '--standard=PSR12 --runtime-set ignore_warnings_on_exit 1 .'
